import Head from 'next/head';
import { Inter } from '@next/font/google';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ newsResults, randomUsers }) {
  return (
    <>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen max-w-7xl mx-auto">
        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}
        <Feed />

        {/* Widgets */}
        <Widgets
          newsResults={newsResults.articles}
          randomUsersResults={randomUsers.results}
        />

        {/* Modal */}
      </main>
    </>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  // news section - widgets
  const newsResults = await fetch(
    'https://saurav.tech/NewsAPI/top-headlines/category/business/us.json'
  ).then((res) => res.json());

  // who to follow - widgets
  const randomUsers = await fetch(
    'https://randomuser.me/api/?results=50&inc=name,login,picture'
  ).then((res) => res.json());

  return {
    props: {
      newsResults,
      randomUsers,
    },
  };
}
